env:
  embedding_size: 128
  action_space_size: 2 # 0: Out, 1: In
  reward_params:
    correct_in: 1.0
    correct_out: 0.1
    false_pos: -0.5
    false_neg: -1.0
    duration_bonus: 0.01

training:
  total_timesteps: 200000
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 128
  gamma: 0.99
  model_dir: "models/rl_v2"

data:
  precomputed_dir: "data/precomputed/*.parquet"
  start: "2018-01-01"
  end: "2024-12-31"
